### ISSUE TITLE
How to obtain Deformable DETR pretrained model (hidden_dim_288)

### ISSUE THREAD

**Issue by guanw-pku** [timmeinhardt/trackformer#105]
I got an error when loading pretrained deformable detr weight [r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth]. How to obtain the pretrained weight [r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_hidden_dim_288.pth] used here?

**Comment by timmeinhardt** [comment]
What error did you get?

The `r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_hidden_dim_288.pth` weights are in our model file zip. You can find the download instructions in our `docs/INSTALL.md`.

**Comment by guanw-pku** [comment]
Thanks a lot!
