### ISSUE TITLE
pre-trained deformable DETR

### ISSUE THREAD

**Issue by mahdiabdollahpour** [timmeinhardt/trackformer#19]
Hi

It is said in the paper that "We follow [58] and pre-train the model for 50 epochs without track queries on COCO [26]."
Do you use pre-trained models from https://github.com/fundamentalvision/Deformable-DETR, or do you pre-train it yourself?
In case you use models from https://github.com/fundamentalvision/Deformable-DETR, which one exactly do you use?
If you pre-train it yourself on COCO, is the COCO pre-training script also included in the repository?

Thanks

**Comment by timmeinhardt** [comment]
We use the pretrained model from the Deformable DETR repository. In the configuration file for the CrowdHuman pretraining you can find the corresponding `resume` setting: 
https://github.com/timmeinhardt/trackformer/blob/ee6982c3f27f63feb6aea78fb5c8dfa02284b137/cfgs/train_crowdhuman.yaml#L6
