### ISSUE TITLE
How to train with distributed mode

### ISSUE THREAD

**Issue by lsabrinax** [timmeinhardt/trackformer#2]
I want to train trackformer on one machine with multi GPUs using DDP? So how can I enable distributed mode in the command line, when I add `python -m torch.distributed.launch --nproc_per_node=4` before `src/train.py` then it asserts `subprocess.CalledProcessError`, can anyone help me?. Thanks firstly.

**Comment by timmeinhardt** [comment]
I think your command is just missing the `--use_env` flag. For example:

```
python -m torch.distributed.launch --nproc_per_node=8 --use_env src/train.py with \
    deformable \
    tracking \
    crowdhuman \
    full_res \
    output_dir=models/crowdhuman_train_val_deformable ```

**Comment by timmeinhardt** [comment]
Can we close this issue?
