### ISSUE TITLE
Is there a pretrained weight file based on vanilla DETR?

### ISSUE THREAD

**Issue by PhanTask** [timmeinhardt/trackformer#21]
The pretrained weight files of Trackformer currently are all based on Deformable DETR. However, my current environment does not support Deformable DETR due to some physical limitations.

Could you please provide a pretrained weight file based on vanilla DETR (e.g., DETR-ResNet-50)? Thanks!

**Comment by timmeinhardt** [comment]
Are you referring to a model file pretrained on CrowdHuman or COCO detection? The latter can be found in the original DETR repository.

**Comment by PhanTask** [comment]
Thank you, @timmeinhardt
I remember for vanilla-DETR-based TrackFormer, there are some additional attention layers (layers_track_attention) for projecting output embeddings to track queries. If I am not mistaken, the pretrained vanilla DETR does not have weights for these layers. Do you have pretrained ready-to-use weight files for vanilla-DETR-based TrackFormer?

**Comment by timmeinhardt** [comment]
We provide the model file for our MOTS20 experiments which are still vanilla-DETR-based. These should include the weights for the additional tracking attention layers. You should be able discard the segmentation head and work with the rest for pure tracking bounding box based tracking.

**Comment by PhanTask** [comment]
@timmeinhardt Great! Thanks a lot!
