### ISSUE TITLE
Using the DEMO code

### ISSUE THREAD

**Issue by ZhiCheng-H** [timmeinhardt/trackformer#26]
This paper is very good! When I use the code of demo interface,I always get mistakes like this:

$ python src/track.py with \
>     dataset_name=DEMO \
>     data_root_dir=data/snakeboard \
>     output_dir=data/snakeboard \
>     write_images=pretty
WARNING - root - Changed type of config entry "write_images" from bool to str
WARNING - track - No observers have been added to this run

In the end, I'll get something like this again:
    if (isinstance(colors[0], Sized) and len(colors[0]) == 2
IndexError: list index out of range

I have created a DEMO folder and put the video I'm going to demonstrate into it, but it still reports this error. I guess it's because the video I put in hasn't been converted to coco format?

But when I demonstrate, I should be able to enter any video and get visual results rather than having to convert it to Coco format.

I'm very confused.How can I solve the problem?

**Comment by timmeinhardt** [comment]
Can you please post the full error log and did you convert the video to frame images? The README includes how to do this: `ffmpeg -i data/snakeboard/snakeboard.mp4 -vf fps=30 data/snakeboard/%06d.png`

**Comment by ZhiCheng-H** [comment]
> Can you please post the full error log and did you convert the video to frame images? The README includes how to do this: `ffmpeg -i data/snakeboard/snakeboard.mp4 -vf fps=30 data/snakeboard/%06d.png`

Thank you for your timely answer. I am sorry that I forget to convert it into a picture.

**Comment by timmeinhardt** [comment]
No worries! If it works now we can close this issue?

**Comment by ZhiCheng-H** [comment]
> No worries! If it works now we can close this issue?
OK. Thank you again.

**Comment by zhoutianxiang-coder** [comment]
i have convertd the video  into a picture.  but still get the same problem

**Comment by timmeinhardt** [comment]
Maybe the images are in the wrong directory?

**Comment by zhoutianxiang-coder** [comment]
![image](https://github.com/timmeinhardt/trackformer/assets/150003658/f4894c66-f629-4cae-ae7a-9518a7728bc4)
I followed the instructions on the readme to split the video into images and save the images in the snakeboard folder

**Comment by timmeinhardt** [comment]
Are your images in the `DEMO` folder?

**Comment by zhoutianxiang-coder** [comment]
I put the image in the sakeboard file where the original video was, do I need to put the image in the demo folder?

发件人：Tim Meinhardt ***@***.***>
发送日期：2023-11-06 16:42:03
收件人：timmeinhardt/trackformer ***@***.***>
抄送人：zhoutianxiang-coder ***@***.***>,Comment ***@***.***>
主题：Re: [timmeinhardt/trackformer] Using the DEMO code (Issue #26)

Are your images in the DEMO folder?

**Comment by timmeinhardt** [comment]
Image or Images? And are the snakeboard files still there? Where you able to run the snakeboard demo?

**Comment by zhoutianxiang-coder** [comment]
![image](https://github.com/timmeinhardt/trackformer/assets/150003658/3576dcb8-0326-4b4a-b372-2092239dcb2f)
![image](https://github.com/timmeinhardt/trackformer/assets/150003658/76c2e122-7642-47f2-866f-99953fcf6105)
As shown in the picture above, I still put the finished pictures in the sakeboard, and then directly run the README command .
Is the video divided into 131 pictures?

**Comment by timmeinhardt** [comment]
Where you able to run the snakeboard demo?
Our code outputs individual frames not a video file.

**Comment by zhoutianxiang-coder** [comment]
What do you mean by where it runs? It's just the left side of the readme command and waiting to click to run

**Comment by timmeinhardt** [comment]
Sorry "Were you able ..."

**Comment by zhoutianxiang-coder** [comment]
Let me reiterate what I did: first I split the videos in Snakeboard into images according to the prompts on the readme, which I still save in the Snakeboard folder. Then I run the track.py file according to the instructions, which are shown in the image. But there is an error like the one above.

**Comment by zhoutianxiang-coder** [comment]
![image](https://github.com/timmeinhardt/trackformer/assets/150003658/af2e0a14-b781-4e45-b012-988b20728f78)
![image](https://github.com/timmeinhardt/trackformer/assets/150003658/d37d079a-f36c-4a71-9b8d-127232c42d84)

**Comment by timmeinhardt** [comment]
In which directory are u executing this? There is some path issue that you have to figure out by going into the code and debugging.

**Comment by zhoutianxiang-coder** [comment]
Is this error due to the path? Is it the reason why the pictures were not found?I performed the operation in the main directory of the project, which is the trackformer-mian directory。What is the reason for this error?

**Comment by zhoutianxiang-coder** [comment]
How to detect my own dataset images and obtain corresponding visualization results？

**Comment by zhoutianxiang-coder** [comment]
I am operating under Windows, is that why?

**Comment by zhoutianxiang-coder** [comment]
![image](https://github.com/timmeinhardt/trackformer/assets/150003658/e94e44dc-1741-402d-b702-23f13fa350ac)
When I don't add write_images=pretty command is used, the running result is shown in the above figure

**Comment by timmeinhardt** [comment]
This is a path issue of some sort. A few print/debug statements in the track.py file and you will figure this out. Beyond that I can not help you.

**Comment by zhoutianxiang-coder** [comment]
ok，i will try. tank you for your help.

**Comment by zhoutianxiang-coder** [comment]
ok, i will try. thank you so much for your help

**Comment by zhoutianxiang-coder** [comment]
May I ask how to display his ID number on the tracking box? The color of the box is used to distinguish different ID numbers
