### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by Soyad-yao** [timmeinhardt/trackformer#28]
### **Hello, when i finished all the requirements installed,when compile the module i met this error.**
_`/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
       __p->_M_set_sharable();
[error.txt](https://github.com/timmeinhardt/trackformer/files/7574404/error.txt)

       ~~~~~~~~~^~
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
ninja: build stopped: subcommand failed.`_
**i am not sure what i can do to address this issue so ask help for people who are solve this problem correctly,Thank you! 
and my system configuration is as follows:
Ubuntu 18.04 LTS
cuda 10.1
pytorch 1.5**

**Comment by Soyad-yao** [comment]
_I have found my solution to solve this problem and now share it with you！_
maybe my gcc version is too high,So it doesn't compile well.
**_locate basic-string.tcc file in this line __p->_M_set_sharable(); and change it to (*__p)._M_set_sharable();_**
Module installed successfully
[succ.txt](https://github.com/timmeinhardt/trackformer/files/7574483/succ.txt)
.

**Comment by timmeinhardt** [comment]
After changing your GCC version you were apply to compile the code?

**Comment by Soyad-yao** [comment]
> After changing your GCC version you were apply to compile the code?

### No,i didn't change the gcc version but change a code in the string.tcc file. and it worked well.

**Comment by timmeinhardt** [comment]
Okay, good if it worked for you. Can we close this issue?

**Comment by Soyad-yao** [comment]
> Okay, good if it worked for you. Can we close this issue?

ok,thanks for your great job.
