### ISSUE TITLE
Class error is very high when using COCO pretrained model with Custom Datasets(VisDrone2019)

### ISSUE THREAD

**Issue by JackWoo0831** [timmeinhardt/trackformer#35]
Hello, Firstly thanks for your brilliant work.
I want to train the TrackFormer in VisDrone2019, which contains objects of vehicles instead of Pedestrians.
Although the object is different, considering that Deformable DETR's pre-trained model (i.e. r50_deformable_detr-checkpoint.pth) should have been pre-trained on the COCO dataset, which contains vehicles. So I think it works.

In converting the VisDrone dataset into COCO format, I only kept the vehicle categories. However, after training two epochs based on r50_deformable_detr-checkpoint.pth model, it was found that class error was basically 100, and various losses did not improve significantly in the later training period. But other evaluation index(such as loss_bbox and loss_ce etc.) seems reasonable,.

During training, it acts like this:
![微信截图_20220303205949](https://user-images.githubusercontent.com/49953745/156570478-897c8c3c-6fd1-4f47-8edf-494cb7fc1769.png)

And after two epoch, the average status is:
![微信截图_20220303210006](https://user-images.githubusercontent.com/49953745/156570619-13bd982e-51b5-49af-b307-372c75e2002a.png)

What is the possible reason for this? or Could you give me some advice?

Thank you very much.

**Comment by mustafaozx** [comment]
@JackWoo0831 Hello there, how you did solve this problem ?

**Comment by timmeinhardt** [comment]
This has most certainly to do with the class index in the model or dataset. Please read the code carefully to adjust your dataset to it. For example, COCO has pedestrians on index 1 and we set this to index 0 in the repo.
