### ISSUE TITLE
Does the model load the whole image sequence into memorry?

### ISSUE THREAD

**Issue by mkhoshle** [timmeinhardt/trackformer#38]
I have a question regarding the way data is loaded into memory for this code. 
Since you are using auto-regressive track queries does that mean all the images on a video sequence are loaded simultaneously into memory?
Or do you load only a specific frame and its previous one into memory at each iteration? I would really appreciate it if you could clarify this for me?

Thanks in advance,

**Comment by timmeinhardt** [comment]
We only load two frames into the memory. The adaptive track queries transfer information from frame to frame.

**Comment by mkhoshle** [comment]
Alright, thanks for the clarification!
