### ISSUE TITLE
Error while using DETR instead of deformable DETR

### ISSUE THREAD

**Issue by senecobis** [timmeinhardt/trackformer#47]
Hi.
I was trying to run trackformer using DETR instead of deformable DETR, I strictly need the first for my application.
I was indeed try to use the pretrained weights for mots20 dataset, as suggested in this issue: [](https://github.com/timmeinhardt/trackformer/issues/21)
The problem arise at the beginning when trying to run the following commands 

`python src/track.py with \
    dataset_name=MOTS20-ALL \
    obj_detect_checkpoint_file=models/mots20_train_masks/checkpoint.pth`

with this additional fields  
        `write_images="pretty", seed=666, interpolate=False,\
        verbose=True, load_results_dir=None,  generate_attention_maps=False,\
        tracker_cfg=tracker_cfg, \
        frame_range={"start":0.0, "end":1.0}, _config="cfgs/track.yaml", _log=None, _run=None,
        obj_detector_model=None `

This is the error that I got...

`raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DETRSegmTracking:
        size mismatch for class_embed.weight: copying a param with shape torch.Size([2, 256]) from checkpoint, the shape in current model is torch.Size([21, 256]).
        size mismatch for class_embed.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([21]).`

My questions on the topic are the following.
- why mots20_train_masks_checkpoint uses a class_embed dimension of 2 ? Is this the expected behavior, or they should be 21 as for the class_embedding of the other models ?
- My specific application requires to use a pretrained DETR on COCO dataset for panoptic-segmentation on your trackformer. Is there a way to achieve such a thing? Use DETR instead of Deformable DETR

EDIT
I suspect the error is something related to number of classes. Indeed changing in build_model of models/__init__.py the number of class to 1, the error goes away, but something else arise : 

`  File "src/new_track.py", line 211, in main
    tracker.step(frame_data)
  File "/trackformer/src/trackformer/models/tracker.py", line 308, in step
    outputs, _, features, _, _ = self.obj_detector(img, target, self._prev_features[0])
TypeError: forward() takes from 2 to 3 positional arguments but 4 were given`
 
My additional question is ...
- Since DETR can take typically as input an image without target and self._prev_features[0], how we should modify the models to use again DETR ?

**Comment by timmeinhardt** [comment]
We are aware of the issues with the MOTS20 DETR model and are currently working on providing a MOTS20 Deformable DETR model. If you must use the DETR model, you need to work with the codebase from commit `958cf89a3d912182e0a67327b493c34232ca8ec4` cause there are other changes that currently prevent the provided MOTS20 DETR model weights from working.

**Comment by senecobis** [comment]
Thanks for the reply.
Starting from commit `958cf89a3d912182e0a67327b493c34232ca8ec4` makes able to use DETR instead of deformable DETR. To make it work, from my side, I had to change also the forward pass call, specifying as input (img, target) without previous features both in tracker and detr_tracking: `out, targets, features, memory, hs  = super().forward(samples, targets) `
