### ISSUE TITLE
TypeError: _safe_repr() missing 1 required positional argument: 'sort_dicts'

### ISSUE THREAD

**Issue by abhik-nd** [timmeinhardt/trackformer#55]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
None
2. what exact command you run:
Copy pasted from MOT17 Section of README.md:
```
python src/track.py with \
    reid \
    tracker_cfg.public_detections=min_iou_0_5 \
    obj_detect_checkpoint_file=models/mot17_deformable_multi_frame/checkpoint_epoch_50.pth
```
4. what you observed (including __full logs__):
```
WARNING - root - Changed type of config entry "tracker_cfg.public_detections" from bool to str
WARNING - track - No observers have been added to this run
INFO - track - Running command 'main'
INFO - track - Started
ERROR - track - Failed after 0:00:00!
Exception originated from within Sacred.
Traceback (most recent calls):
  File "/home/abhik/anaconda3/envs/trackformer/lib/python3.8/site-packages/sacred/commands.py", line 61, in _non_unicode_repr
    repr_string, isreadable, isrecursive = pprint._safe_repr(
TypeError: _safe_repr() missing 1 required positional argument: 'sort_dicts'
srun: error: node001: task 0: Exited with exit code 1
```

6. please simplify the steps as much as possible so they do not require additional resources to

## Solution
This bug 
https://github.com/IDSIA/sacred/issues/780

Simply update requirements.txt to sacred==0.8.2 or higher instead of sacred ==0.8.2

**Comment by timmeinhardt** [comment]
Please have a look at [this](https://github.com/phil-bergmann/tracking_wo_bnw/issues/135) issue. (The first result after searching your error in Google).

**Comment by abhik-nd** [comment]
thanks for your quick response. didn't see this repo was tested with python 3.7
