### ISSUE TITLE
Why don't the track queries get updated for two_stage?

### ISSUE THREAD

**Issue by owen24819** [timmeinhardt/trackformer#61]
https://github.com/timmeinhardt/trackformer/blob/d62d81023dbffb4a1820db39ce527b66df6d7b61/src/trackformer/models/deformable_transformer.py#L180-L230

I am confused why the track queries don't get updated for the two-stage. 

Also, nice work by the way!

**Comment by timmeinhardt** [comment]
TrackFormer is not implemented to work with the two-stage approach of Deformable DETR. In my opinion, the two-stage approach is a step back from the end-to-end unified solution of DETR. Hence, we never tried to combine two-stage with our track query approach.

**Comment by owen24819** [comment]
Ah ok. I see. Thanks for the quick response!

Following up with another question, does TrackFormer work with num_feature_levels greater than 1. It makes sense why you chose 1 feature level however I would like to try more feature levels. Although I could run MultiScaleDeformableAttention with multiple feature levels on Trackformer, I noticed the  MultiScaleDeformableAttention package  was  differenent from the Deformable DETR paper. Is it ok to use your MultiScaleDeformableAttention package for multiple feature levels or should I revert back to the Deformable DETR's  MultiScaleDeformableAttention package.

**Comment by timmeinhardt** [comment]
TrackFormer already works with multiple feature levels. All our trainings/evaluations (except the MOTS20 models) run the `deformable` option which loads [this](https://github.com/timmeinhardt/trackformer/blob/main/cfgs/train_deformable.yaml) config. 

The underlying MultiScaleDeformableAttention backend should not make a big difference.

**Comment by owen24819** [comment]
Great! Thanks a lot!
