### ISSUE TITLE
DETRTracking in backprob only mode

### ISSUE THREAD

**Issue by taxy** [timmeinhardt/trackformer#69]
https://github.com/timmeinhardt/trackformer/blob/d62d81023dbffb4a1820db39ce527b66df6d7b61/src/trackformer/models/detr_tracking.py#L224

In what situation might this condition be needed?

We can no longer be in tracking mode here, because of upper if. But you may need an augmented previous frame, even if you are training currently not this model, but training other model depends on it.

**Comment by taxy** [comment]
I made a separated _training_session property, for separate it from pytorch model training property

**Comment by timmeinhardt** [comment]
https://github.com/timmeinhardt/trackformer/blob/d62d81023dbffb4a1820db39ce527b66df6d7b61/src/trackformer/models/detr_tracking.py#L263
In this line it says that we need this if to evaluate the per-frame detection performance of our model.

**Comment by taxy** [comment]
> https://github.com/timmeinhardt/trackformer/blob/d62d81023dbffb4a1820db39ce527b66df6d7b61/src/trackformer/models/detr_tracking.py#L263
> 
> In this line it says that we need this `if` to evaluate the per-frame detection performance of our model. So if tracking is disabled and we are not training the model works like a single image object detector.

oh, it just doesn't poke out my eye. Thank you!
