### ISSUE TITLE
Pretrained ablation model

### ISSUE THREAD

**Issue by sieumap43** [timmeinhardt/trackformer#71]
Hi. Thanks a lot for the great work.
Can you also provide the pre-trained models in the ablation study, e.g. the model trained on CrowdHuman + half of MOT17? I don't have the GPUs to re-trained your ablation models.
Many thanks.

**Comment by timmeinhardt** [comment]
Hello and thank you for your interest in our work. Unfortunately, we are not going to release the intermediate ablation models.
