### ISSUE TITLE
Need for both COCO format and MOT format data for training?

### ISSUE THREAD

**Issue by HassanAliAnsari** [timmeinhardt/trackformer#73]
Hi! Amazing work! 
Quick question; While training Trackformer, are you using both COCO format and MOT format data? COCO format for object detection and MOT format for tracking?
I want to train Trackformer for multi-class multi-object tracking and I have prepared my dataset in COCO format. However, when I look at the train.py I see that 'evaluate' function is being called ([at line 299](https://github.com/timmeinhardt/trackformer/blob/e1dbc2536b86348c2f62c788c98a2faf06247147/src/train.py#L299)) which eventually calls TrackDatasetFactory. Why do we need to create a separate dataloader for the tracker that expects a different format (MOT format and not the already made COCO format)?

**Comment by timmeinhardt** [comment]
The two formats are for evaluation purposes. We train in COCO format modified to include tracking ids. But the evaluation code requires MOT format. Once could unify this but at the time this was the easier solution.

**Comment by HassanAliAnsari** [comment]
Great!
Thank you for clarifying!

**Comment by tostenzel** [comment]
Hey @HassanAliAnsari, I am at the same point now. How did you proceed from there?

**Comment by HassanAliAnsari** [comment]
> Hey @HassanAliAnsari, I am at the same point now. How did you proceed from there?

I unified both COCO and MOT dataloaders into one. I wrote dataloader which used the same COCO format for tracker.

**Comment by tostenzel** [comment]
@HassanAliAnsari Ah that sounds great. Can you potentially share the respective code changes with me?

Edit for later user: Got it done with an additional dataset in MOT format...
