### ISSUE TITLE
Full name of hs_embed

### ISSUE THREAD

**Issue by sieumap43** [timmeinhardt/trackformer#74]
Hi. I just want to know what is the full name of the word hs_embed. I know that that is the queries (object and track queries) but what is "hs"?

**Comment by timmeinhardt** [comment]
I never thought about it. But maybe sth related to hidden size or space? This notation is a relict from the original [DETR](https://github.com/facebookresearch/detr) repository. Maybe ask them directly but in the end it does not really matter, right?
