### ISSUE TITLE
the problem when i track mots20-all

### ISSUE THREAD

**Issue by niangea** [timmeinhardt/trackformer#78]
when i use "python src/track.py with \
    dataset_name=MOTS20-ALL \
    obj_detect_checkpoint_file=models/mots20_train_masks/checkpoint.pth"

-----------------------------------------------------------------------------------------------------------------------------------------------
I get "
ERROR - track - Failed after 0:00:26!
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/track.py", line 91, in main
    obj_detector.load_state_dict(obj_detect_state_dict)
  File "/home/lihenian/.conda/envs/bishe37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DETRSegmTracking:
        size mismatch for class_embed.weight: copying a param with shape torch.Size([2, 256]) from checkpoint, the shape in current model is torch.Size([21, 256]).
        size mismatch for class_embed.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([21]).
"
----------------------------------------------------------------------------------------------------------------------------------------------
this is my environment

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.17

Python version: 3.7.16 (default, Jan 17 2023, 22:20:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.6
[pip3] torch==1.13.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.14.1
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by taxy** [comment]
Number of class heads are different between model and saved wieghts

**Comment by niangea** [comment]
> Number of class heads are different between model and saved wieghts

What command should I use

**Comment by taxy** [comment]
> > Number of class heads are different between model and saved wieghts
> 
> What command should I use

https://github.com/timmeinhardt/trackformer/blob/e1dbc2536b86348c2f62c788c98a2faf06247147/cfgs/train_mots20.yaml#L6
I think you have a problem with the checkpoint file, the relevant config gives the answer

**Comment by niangea** [comment]
> > > Number of class heads are different between model and saved wieghts
> > 
> > 
> > What command should I use
> 
> https://github.com/timmeinhardt/trackformer/blob/e1dbc2536b86348c2f62c788c98a2faf06247147/cfgs/train_mots20.yaml#L6
> 
> 
> I think you have a problem with the checkpoint file, the relevant config gives the answer

but i can not find this model in trackformer_models_v1.zip,
how can I find this model?

**Comment by taxy** [comment]
> 

it is possible that the readme is out of date, and not all  trains are available anymore.  ☹️ I only tried one before using it

**Comment by niangea** [comment]
> > 
> 
> it is possible that the readme is out of date, and not all trains are available anymore. ☹️ I only tried one before using it

Have you tried it on mot17? After I tested four data on mot17, I received the error message, and then uploaded the issue

**Comment by timmeinhardt** [comment]
MOT17 is tested and works. But I have to admit that the MOTS20 models/code were not thoroughly tested after the last larger code changes. In order to make it work one has to add an exception [here](https://github.com/timmeinhardt/trackformer/blob/e1dbc2536b86348c2f62c788c98a2faf06247147/src/trackformer/models/__init__.py#L16) initializing with `num_classes = 1`. To see if this helps you could hardcode it for a start.

**Comment by maxploter** [comment]
@timmeinhardt 
should we initialise with `num_classes = 2` as we have a dataset that has a single class with id 1 (person)?

>     # As another example, for a dataset that has a single class with id 1,
>     # you should pass `num_classes` to be 2 (max_obj_id + 1).
>     # For more details on this, check the following discussion
>     # https://github.com/facebookresearch/detr/issues/108#issuecomment-650269223

https://github.com/facebookresearch/detr/blob/29901c51d7fe8712168b8d0d64351170bc0f83e0/models/detr.py#L309-L312

I wonder why we decrement target label? I think pre trained Deter will outputs label 1 for person.
https://github.com/timmeinhardt/trackformer/blob/e468bf156b029869f6de1be358bc11cd1f517f3c/src/trackformer/datasets/coco.py#L241
