### ISSUE TITLE
wrongly load prev_frame image and target in `MOT.__getitem__`

### ISSUE THREAD

**Issue by lsabrinax** [timmeinhardt/trackformer#8]
![image](https://user-images.githubusercontent.com/17122734/120989150-cef16f00-c7b1-11eb-901a-d271f3ee25a4.png)
because `no_obj_imgs` removed from self.ids, the ids has a new map relation between img_id. the above code will get wrong prev_frame image_id

**Comment by timmeinhardt** [comment]
In this line the `CocoDetection` parent class if always called with `remove_no_obj_imgs=False` for the `MOT` class:

https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/datasets/mot.py#L24

That is why for MOT no frame is removed from `self.ids` and the `prev_image_id` should be correct.

**Comment by lsabrinax** [comment]
yes, you are right. Then how these images which do not include any objects attend to the training process. Because they don't have any annotations, won't they affect the model performance？ Thank you for your reply.

**Comment by timmeinhardt** [comment]
There are only very few frames without any objects but this is generally something that might even happen from the random cropping data augmentation. So no, these do not effect the model training in a deteriorating way. The model just learns to not predict/track any objects in these scenarios.

**Comment by lsabrinax** [comment]
Thank your for your patient reply
