### ISSUE TITLE
Should `track_prev_frame_range` be equal to 1 to reproduce paper's results?

### ISSUE THREAD

**Issue by aryan-f** [timmeinhardt/trackformer#80]
Hi.
Thank you for sharing your work.
I was going through the configuration files, and it seems that `track_prev_frame_range` is by default set to 5. However, in the paper (as far as I understood) you state that you are only feeding the previous immediate frame (or a few frames further back, in case of augmentation) to the model. Does this mean this value should be set to 1 (or 2) to reproduce your work?

**Comment by timmeinhardt** [comment]
You are mixing up two different concepts. `track_prev_frame_range` specifies the range from which we sample. but we only sample 1 (or 2 if `multi_frame_attention=true`) frames. See the `track augmentations` section for infos regarding the frame range.

**Comment by aryan-f** [comment]
Got it! Thanks for the help.
