### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by niangea** [timmeinhardt/trackformer#85]
when I use "python src/train.py with     mot17     deformable     multi_frame     tracking   output_dir=models/mot17_deformable_multi_frame"
I get this error"
Traceback (most recent call last):
  File "src/train.py", line 356, in <module>
    train(args)
  File "src/train.py", line 283, in train
    visualizers['train'], args)
  File "/home/lihenian/trackformer-main/src/trackformer/engine.py", line 126, in train_one_epoch
    outputs, targets, *_ = model(samples, targets)
  File "/home/lihenian/.conda/envs/bishe37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lihenian/trackformer-main/src/trackformer/models/detr_tracking.py", line 261, in forward
    self.add_track_queries_to_targets(targets, prev_indices, prev_out)
  File "/home/lihenian/trackformer-main/src/trackformer/models/detr_tracking.py", line 94, in add_track_queries_to_targets
    prev_boxes_matched = prev_out['pred_boxes'][i, prev_out_ind[target_ind_matching]]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
"
this is my environment

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.17

Python version: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.6
[pip3] torch==1.13.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.14.1
[conda] numpy 1.21.6 pypi_0 pypi
[conda] torch 1.13.1 pypi_0 pypi
[conda] torchfile 0.1.0 pypi_0 pypi
[conda] torchvision 0.14.1 pypi_0 pypi

**Comment by timmeinhardt** [comment]
As the error message is indicating, you are trying to run the code on CPU.

**Comment by Lvobsessives** [comment]
I'm also having this problem, my cuda version is also 11.7, please how to fix it

**Comment by mlx-xxdm** [comment]
I'm also having this problem,, please how to fix it

**Comment by AlirezaKh1990** [comment]
Same problem
