### ISSUE TITLE
Where to find checkpoints ?

### ISSUE THREAD

**Issue by maximereder** [timmeinhardt/trackformer#92]
Hi,

I am trying to use the Trackformer architecture. I done all installation. 

Now, I'm running :
`!python src/track.py with \
    reid \
    tracker_cfg.public_detections=min_iou_0_5 \
    obj_detect_checkpoint_file=models/mot17_deformable_multi_frame/checkpoint_epoch_50.pth`
    
But I have the following error : 
`FileNotFoundError: [Errno 2] No such file or directory: 'models/mot17_deformable_multi_frame/config.yaml'`

It seems missing checkpoints. Where we can download models ? 

Thanks,

Maxime.

**Comment by timmeinhardt** [comment]
Please check step 4 of the [INSTALL.md](https://github.com/timmeinhardt/trackformer/blob/main/docs/INSTALL.md).
