### ISSUE TITLE
How to generate segm results

### ISSUE THREAD

**Issue by niangea** [timmeinhardt/trackformer#97]
How to generate segm results by Trackformer

**Comment by timmeinhardt** [comment]
Please read our documentation and the config files. There are instructions on how to run MOTS20 which is with masks. But you need a different model file. Before asking questions as general as these please take some time to make yourself more familiar with the code and repository.

**Comment by niangea** [comment]
Thanks

**Comment by niangea** [comment]
Where can I get the model of that mask

**Comment by timmeinhardt** [comment]
Its in the same zip  file with the other models. But its a different configuration. See the related section in the paper. And please keep the issue commenting to a minimum. We can not debug every step with you!
